const questions = [
  { id: 1, text: "Czy Twoja skóra często się błyszczy?" },
  { id: 2, text: "Czy Twoja skóra jest szorstka w dotyku?" },
  { id: 3, text: "Czy masz widoczne pory na całej twarzy?" },
  { id: 4, text: "Czy Twoja skóra jest cienka i delikatna?" },
  { id: 5, text: "Czy zauważyłeś/aś czerwone plamy na swojej skórze?" },
  { id: 6, text: "Czy masz tendencję do pojawiania się wyprysków?" },
  { id: 7, text: "Czy Twoja skóra reaguje szybko na zmiany temperatury?" },
  { id: 8, text: "Czy Twoja skóra jest często sucha i potrzebuje nawilżenia?" },
  { id: 9, text: "Czy Twoja skóra ma matowy koloryt?" },
  { id: 10, text: "Czy po umyciu twarzy odczuwasz ściągnięcie skóry?" },
  { id: 11, text: "Czy Twoja skóra jest niejednolita i ma przebarwienia?" },
  { id: 12, text: "Czy skóra wokół oczu jest szczególnie cienka i delikatna?" },
  { id: 13, text: "Czy pojawiają się u Ciebie zmarszczki mimiczne?" },
  { id: 14, text: "Czy Twoja skóra jest narażona na alergie skórne?" },
  { id: 15, text: "Czy Twoja skóra często staje się czerwona?" },
  { id: 16, text: "Czy masz często uczucie napięcia skóry?" },
  { id: 17, text: "Czy Twoja skóra jest gruba i ma nierówną teksturę?" },
  {
    id: 18,
    text: "Czy Twoja skóra jest dobrze nawilżona bez stosowania kremów?",
  },
  {
    id: 19,
    text: "Czy masz powiększone pory w strefie T (czoło, nos, broda)?",
  },
  { id: 20, text: "Czy masz często uczucie gorąca na skórze twarzy?" },
];
